---
Name: app
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SilverStripe\View\SSViewer:
  themes:
    - '$public'
    - 'app'
    - '$default'

# Use utf8mb4 rather than utf8 for MySQL connections - this ensures some Asian languages and emojis are supported
# See https://github.com/silverstripe/silverstripe-framework/issues/8062
SilverStripe\ORM\Connect\MySQLDatabase:
  connection_charset: utf8mb4
  connection_collation: utf8mb4_unicode_ci
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
