---
Name: approutes
After:
 - '#rootroutes'
 - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'search//$Action': 'PageController'
    'news-and-events//$Action': 'App\Controller\CustomTaxonomyDirectoryController'
