---
Name: approutes
After:
 - '#rootroutes'
 - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
  #  'profile//$Action//$ID': 'App\Controller\StaffPageController'
   '$Action//?q=$query': 'App\Controller\SearchController'
